### ISSUE TITLE
Multiple pages - referential integrity

### ISSUE THREAD

**Issue by kevinv11n** [barryhughes1/pluralSightQuestionnaires_LWCs#1]
On https://github.com/barryhughes1/pluralSightQuestionnaires_LWCs/wiki/28.-CRUD-Operations-in-Lightning-Web-Components you introduce the concept of referential integrity by using `@salesforce/schema` modules. To benefit from referential integrity (like having field renames cascaded into your code) you need to use the imported values. The provided code does not do this consistently. Any time you use `"Name"` or `"Id"` you should use the imported values. 

A couple examples (this is not complete).

*Example 1*

```
const ACCOUNT_FIELDS = [
   'Account.Name'
];
```
should be
```
const ACCOUNT_FIELDS = [
   ACCOUNT_NAME_FIELD
];
```

*Example 2*
```
    createAccount() {
        ...
        createRecord(recordInput)
            .then(Account => {
                console.log('createAccount SAVED');
                console.log(JSON.stringify(Account));
                this.accountId = Account.id;
                this.accountName = Account.fields.Name.value;   
```
becomes
```
    createAccount() {
        ...
        createRecord(recordInput)
            .then(Account => {
                console.log('createAccount SAVED');
                console.log(JSON.stringify(Account));
                this.accountId = Account.id;
                this.accountName = Account.fields[ACCOUNT_NAME_FIELD.fieldApiName].value;   
```
But would be even better as
```
    createAccount() {
        ...
        createRecord(recordInput)
            .then(Account => {
                console.log('createAccount SAVED');
                console.log(JSON.stringify(Account));
                this.accountId = Account.id;
                this.accountName = getFieldValue(Account, ACCOUNT_NAME_FIELD);
```

*Example 3*
```
updateAccount() {
        console.log('updateAccount');
        let record = {
              fields: {
                  Id: this.accountId,
                  Name:this.newAccountName
                },
          };
  ```

becomes

```
updateAccount() {
        console.log('updateAccount');
        let record = {
              fields: {
                  Id: this.accountId, // you could also import the Id field but this will never change per Lightning Platform semantics
                  [ACCOUNT_NAME_FIELD]:this.newAccountName
                },
          };
```  

Similar issues are present on:
* https://github.com/barryhughes1/pluralSightQuestionnaires_LWCs/wiki/29.-Inserting-a-Questionnaire-Return-record
* https://github.com/barryhughes1/pluralSightQuestionnaires_LWCs/wiki/30.-Updating-a-Questionnaire-Return-record
* https://github.com/barryhughes1/pluralSightQuestionnaires_LWCs/wiki/31.-Creating-and-Updating-Questionnaire-Answers

**Comment by barryhughes1** [comment]
I have updated the wiki pages and code for this purpose. Also the last wiki step was updated. Thanks @kevinv11n
