### ISSUE TITLE
development settings and cache invalidation

### ISSUE THREAD

**Issue by kevinv11n** [barryhughes1/pluralSightQuestionnaires_LWCs#2]
In the Pluralsight course you use a Chrome extension to clear the browser's cache whenever you push updates to the LWC components. This can be avoided by enabling Lightning Debug Mode  in the Setup tree. This can be directly accessed at `https://hostname/lightning/setup/UserDebugModeSetup/home`.

**Comment by barryhughes1** [comment]
Thanks @kevinv11n - I will add this (and a screenshot of same to the wiki).

**Comment by barryhughes1** [comment]
@kevinv11n - I have updated Step 2 with an extra note on this point.
