### ISSUE TITLE
page 29 - do not trust the browser

### ISSUE THREAD

**Issue by kevinv11n** [barryhughes1/pluralSightQuestionnaires_LWCs#3]
A malicious user can change the Javascript evaluated in their browser so you must not trust it. On page 29 you have code like this:
```
import Id from '@salesforce/user/Id';
...
fields[ANSWERED_BY_FIELD.fieldApiName] = Id;  // from import
```

A malicious user can change the value assigned to the `Answered_By__c` field. Instead of having such a field consider using the built-in `CreatedById` field which is automatically populated with user that creates the record.

**Comment by barryhughes1** [comment]
Good point - I had not considered that. I will update the repo and wiki. Thanks @kevinv11n

**Comment by barryhughes1** [comment]
Thanks @kevin. I have left a note in the wiki page pointing this out. In my example, I am simply showing how the currently logged in user ID can be retrieved via an import - where in the aura it required an apex method call.

Your point is well taken though and indeed the javascript could be manipulated to fill in a different user id.
